In [1]:
import tensorflow as tf
from tensorflow import keras

In [4]:
 class Linear(keras.layers.Layer):
  def __init__(self,units=32,input_dim=32):
    super(Linear,self).__init__()
    w_init=tf.random_normal_initializer()
    self.w= tf.Variable(
         initial_value=w_init(shape=(input_dim,units),dtype="float32"),
         trainable=True
    )
    b_init = tf.zeros_initializer()
    self.b= tf.Variable(
        initial_value= b_init(shape=(units,),dtype="float32"),
        trainable=True
    )
  def call(self,inputs):
    return tf.matmul(inputs,self.w)+self.b


In [6]:
x = tf.ones((2,2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [18]:
linearLayer = Linear(4,2)
y = linearLayer(x)
print(y)

tf.Tensor(
[[ 0.03456577  0.04087431 -0.12532598 -0.02131063]
 [ 0.03456577  0.04087431 -0.12532598 -0.02131063]], shape=(2, 4), dtype=float32)


In [15]:
from tensorflow.python.ops.init_ops_v2 import Initializer
import tensorflow as tf
from tensorflow import keras

class Linear(keras.layers.Layer):
  def __init__(self,units=32,input_dim=32):
    super(Linear,self).__init__()
    self.w= self.add_weight(
        shape=(input_dim,units),initializer="random_normal",trainable=True
    )
    self.b= self.add_weight(shape=(units,),initializer="zeros",trainable=True)

  # The call method should be at the same indentation level as the __init__ method
  def call(self,inputs):
    return tf.matmul(inputs,self.w)+self.b

In [16]:
x = tf.ones((2,2))



In [17]:
linearLayer = Linear(4,2)
y = linearLayer(x)
print(y)

tf.Tensor(
[[ 0.12009541  0.02288961 -0.10448422  0.08352651]
 [ 0.12009541  0.02288961 -0.10448422  0.08352651]], shape=(2, 4), dtype=float32)


In [21]:
class Linear(keras.layers.Layer):
  def __init__(self,units=32):
    super(Linear,self).__init__()
    self.units=units

  def build(self,input_shape):
    self.w= self.add_weight(shape=(input_shape[-1],self.units),initializer="random_normal",trainable=True)
    self.b= self.add_weight(shape=(self.units,),initializer="random_normal",trainable=True)

  # The call method is moved outside the build method and is at the same level as __init__
  def call(self,inputs):
    return tf.matmul(inputs,self.w)+self.b

In [22]:
linearLayer = Linear(32)
y = linearLayer(x)
print(y)

tf.Tensor(
[[-0.00315982 -0.01779896 -0.00869286  0.12356776 -0.00123605 -0.05849227
   0.02261701  0.07155298 -0.06774407  0.07670748 -0.02089366  0.04806242
  -0.16163345  0.10447032  0.06415038 -0.06264547  0.14139558 -0.05084773
   0.05876032  0.07254338 -0.06993999 -0.01565946  0.26746646  0.021034
   0.00281844 -0.11025833  0.2023917  -0.05616361 -0.01356917 -0.04071247
   0.04206007 -0.07255585]
 [-0.00315982 -0.01779896 -0.00869286  0.12356776 -0.00123605 -0.05849227
   0.02261701  0.07155298 -0.06774407  0.07670748 -0.02089366  0.04806242
  -0.16163345  0.10447032  0.06415038 -0.06264547  0.14139558 -0.05084773
   0.05876032  0.07254338 -0.06993999 -0.01565946  0.26746646  0.021034
   0.00281844 -0.11025833  0.2023917  -0.05616361 -0.01356917 -0.04071247
   0.04206007 -0.07255585]], shape=(2, 32), dtype=float32)


In [24]:
class MLP(keras.layers.Layer):
  def __init__(self):
    super(MLP,self).__init__()
    self.linear1 = Linear(32)
    self.linear2 = Linear(32)
    self.linear3 = Linear(10)
  def call(self,inputs):
    x = self.linear1(inputs)
    x = tf.nn.relu(x)
    x = self.linear2(x)
    x = tf.nn.relu(x)
    return self.linear3(x)

In [25]:
mlp = MLP()
y = mlp(tf.ones(shape=(3,64)))
print("Model:",mlp.weights)
print("Model:",mlp.trainable_weights)

Model: [<KerasVariable shape=(64, 32), dtype=float32, path=mlp/linear_8/variable_10>, <KerasVariable shape=(32,), dtype=float32, path=mlp/linear_8/variable_11>, <KerasVariable shape=(32, 32), dtype=float32, path=mlp/linear_9/variable_12>, <KerasVariable shape=(32,), dtype=float32, path=mlp/linear_9/variable_13>, <KerasVariable shape=(32, 10), dtype=float32, path=mlp/linear_10/variable_14>, <KerasVariable shape=(10,), dtype=float32, path=mlp/linear_10/variable_15>]
Model: [<KerasVariable shape=(64, 32), dtype=float32, path=mlp/linear_8/variable_10>, <KerasVariable shape=(32,), dtype=float32, path=mlp/linear_8/variable_11>, <KerasVariable shape=(32, 32), dtype=float32, path=mlp/linear_9/variable_12>, <KerasVariable shape=(32,), dtype=float32, path=mlp/linear_9/variable_13>, <KerasVariable shape=(32, 10), dtype=float32, path=mlp/linear_10/variable_14>, <KerasVariable shape=(10,), dtype=float32, path=mlp/linear_10/variable_15>]
