In [2]:
import tensorflow as tf
import numpy as np
x = tf.range(5)
datasets = tf.data.Dataset.from_tensor_slices(x)
for item in datasets:
    print(item.numpy())


0
1
2
3
4


In [3]:
list(datasets.as_numpy_iterator())

[0, 1, 2, 3, 4]

In [15]:
datasets1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([3,5]))
for eleman in datasets1:
    print(eleman.numpy())



[0.97525346 0.24705505 0.2839991  0.89797044 0.06862295]
[0.3256557  0.14413571 0.06167996 0.9247942  0.92461824]
[0.9499794  0.9573927  0.4034003  0.5874783  0.33796883]


In [8]:
data = [2,3,4,7,-2,8,13]
tf_dataset = tf.data.Dataset.from_tensor_slices(data)
for eleman in tf_dataset.take(3):
    print(eleman.numpy())

2
3
4


In [9]:
for item in tf_dataset.filter(lambda x:x>3):
    print(item.numpy())

4
7
8
13


In [10]:
for item in tf_dataset.map(lambda x:x*2):
    print(item.numpy())

4
6
8
14
-4
16
26


In [11]:
for item in tf_dataset.shuffle(buffer_size=3):
  print(item.numpy())


2
7
4
8
13
3
-2


In [12]:
for item in tf_dataset.batch(2):
  print(item.numpy())


[2 3]
[4 7]
[-2  8]
[13]


In [13]:
dataset = tf.data.Dataset.from_tensor_slices(data) # Pass the 'data' list to the function

In [14]:
dataset = dataset.filter(lambda x: x > 0).map(lambda y: y * 2).shuffle(buffer_size=3).batch(2)
for item in dataset:
  print(item.numpy())

[8 4]
[ 6 26]
[14 16]


In [18]:
flowers_root = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)

228813984/228813984 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [20]:
import pathlib
flowers_root = pathlib.Path(flowers_root)
flowers_root

PosixPath('/root/.keras/datasets/flower_photos')

In [25]:
image_count = len(ds)

In [26]:
train_size = int(image_count * 0.8)
train_ds = ds.take(train_size)
test_ds = ds.skip(train_size)

In [27]:
ds = tf.data.Dataset.list_files(str(flowers_root/'*/*'))
for file in ds.take(5):
    print(file.numpy())

b'/root/.keras/datasets/flower_photos/tulips/17159816388_deafbebdb0.jpg'
b'/root/.keras/datasets/flower_photos/sunflowers/7820305664_82148f3bfb_n.jpg'
b'/root/.keras/datasets/flower_photos/roses/12165480946_c4a3fe182d_n.jpg'
b'/root/.keras/datasets/flower_photos/tulips/16282277874_b92776b194.jpg'
b'/root/.keras/datasets/flower_photos/tulips/5546723510_39a5a10d3a_n.jpg'


In [29]:
for file in ds.take(5):
  print(file.numpy())

b'/root/.keras/datasets/flower_photos/roses/14414117598_cf70df30de.jpg'
b'/root/.keras/datasets/flower_photos/tulips/5674170543_73e3f403fb.jpg'
b'/root/.keras/datasets/flower_photos/tulips/5698944116_fd35fe6bea.jpg'
b'/root/.keras/datasets/flower_photos/roses/9216324117_5fa1e2bc25_n.jpg'
b'/root/.keras/datasets/flower_photos/dandelion/7184780734_3baab127c2_m.jpg'


In [31]:
ds = ds.shuffle(200)

In [33]:
train_size = int(image_count * 0.8)
train_ds = ds.take(train_size)
test_ds = ds.skip(train_size)

In [34]:
len(train_ds)

2936

In [35]:
len(test_ds)

734

In [38]:
def get_label(file_path):
  import os
  parts = tf.strings.split(file_path, os.path.sep)
  return parts[-2]


In [40]:
x = b'/root/.keras/datasets/flower_photos/tulips/17159816388_deafbebdb0.jpg'

In [42]:
get_label(x).numpy()

b'tulips'

In [43]:
def process_path(file_path):
  label = get_label(file_path)
  img = tf.io.read_file(file_path)
  img = tf.image.decode_jpeg(img)
  img = tf.image.resize(img, [128, 128])
  img = img / 255.0
  return img, label
#

In [44]:
img , label = process_path(x)

In [45]:
 img.shape

TensorShape([128, 128, 3])

In [51]:
img[:3,:3,:1]

<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[0.13722092],
        [0.1912119 ],
        [0.17051451]],

       [[0.30648026],
        [0.61871886],
        [0.25209484]],

       [[0.33264446],
        [0.6712594 ],
        [0.3356943 ]]], dtype=float32)>

In [48]:
train_ds = train_ds.map(process_path)
test_ds = test_ds.map(process_path)

In [50]:
for image, label in train_ds.take(1):
  print("Image shape: ", image.numpy())
  print("Label: ", label.numpy())

Image shape:  [[[0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00496324 0.00496324 0.00496324]
  ...
  [0.00680147 0.00680147 0.00680147]
  [0.00757339 0.00757339 0.00757339]
  [0.00855091 0.01210483 0.00603865]]

 [[0.00682277 0.00682277 0.00102036]
  [0.00784314 0.00784314 0.00288517]
  [0.00784314 0.00784314 0.00450368]
  ...
  [0.00724499 0.00724499 0.00724499]
  [0.00784314 0.00784314 0.00784314]
  [0.01009498 0.01343444 0.00543476]]

 [[0.00784314 0.00784314 0.        ]
  [0.00784314 0.00784314 0.        ]
  [0.01176471 0.01176471 0.00968137]
  ...
  [0.01072304 0.01072304 0.01072304]
  [0.01024744 0.01024744 0.01024744]
  [0.00586703 0.01015625 0.00445772]]

 ...

 [[0.02895149 0.04019584 0.03612156]
  [0.05199214 0.09525051 0.07132353]
  [0.0598652  0.11084559 0.07564099]
  ...
  [0.01055453 0.02680042 0.00659874]
  [0.04390319 0.08227635 0.04748775]
  [0.0319087  0.0627609  0.03656652]]

 [[0.03761657 0.06607522 0.05689338]
  [0.05094712 0.0997881